### PR TITLE
Easier on the eyes + dynamic svg menu button color

### PR DESCRIPTION
**Pull request by domfarolino**
- Added `div[view]` padding so mobile has some space on the sides of the view content
 - Added `header` `border-bottom` as per @noahbass request
 - Added card `border-left` for...idk I thought it looked good I guess
 - Added support for body images so spice up our wall o' text in the about (and future) page(s)
 - Added SVG directly in header so we can control its `fill: xxx` property. I made it so it is white (matching the text and theming) when the sidenav is not popped, and then turns black when the sidenav is popped (so the user can see and click it).
 - Add notification button (links to mailchimp)

**Note:** the added text inside the about page was just to test the pictures and how they look floated both to the left and right with a lot of text. If you like the styles, then I'll revert the text/pics back to how it was so we can use the styles later when we need to.

### CODE REVIEW

**Comment by isiah-lloyd** [comment]
Damn it, I was just working on masthead subtitles

**Comment by domfarolino** [comment]
ahh sorry. I should've made an issue so we could discuss and not dupe work. My bad, will next time.

**Comment by domfarolino** [comment]
This branch can be seen live at bosley.club

**Comment by isiah-lloyd** [comment]
Hmmmm, it doesn't really fit the case I wanted it for though. I'm working on #19 which requires multiple information on the masthead. I had it done so the subtitles were given in a array and it looped through each element and created a new line.

**Comment by domfarolino** [comment]
Shit I didn't even pay attention to that issue (or the fact that you were assigned it). I can revert the subtitle stuff from the PR if you want to take it. Check my comment in that issue though. I feel like too many things (enough to make an array) might crowd the mast too much. Not sure though. If you want to come up with a branch go for it and if we dig it I can get rid of the subtitle stuff from here. My bad

**Comment by isiah-lloyd** [comment]
It's no problem, I kinda agree. I'll talk more about it on the issue. But I do think the subtitle font-weight should be smaller than the title.

**Comment by domfarolino** [comment]
Ahh sorry @noah I at-mentioned the wrong person. I'll get you out of here

**Pull request merged**
