### PR TITLE
feature/1.0.0 styles 💥

### LINKED ISSUE #19: Homepage content
Required content:

- Masthead image area:
    - [x]   Name of hackathon (RevolutionUC)
    - [x]    Date (April 8th & 9th, 2017)
    - [x]    Location (University of Cincinnati)

~**Consider** adding masthead media queries so content doens't overlap on small screens~

- Body area

    - [ ]    Rich links to the about page, ~~FAQ page, schedule page, etc~~.
    - [ ]    Sponsors logos and links (include contact info for interested sponsors)
    - [ ]    Social media info
    - [ ]    Contact info

### PR DESCRIPTION
**Pull request by noahbass**
Be sure to run `npm i` after pulling down as there is a new dependency on this branch.

- Updates the home and about page styles
- Adds photos on the home and about pages
- Adds a site footer
- Refactors some sass

Should close #19, #28, and most of #15

### CODE REVIEW

**Comment by domfarolino** [comment]
How do you feel about an orange border-top on the footer to match the border-bottom on header.

**Comment by noahbass** [comment]
I like it. Go for it!

**Comment by domfarolino** [comment]
Just to be clear, most of the already existing styles were just re-arranged but not actually modified right? And then of course other styles (grid stuff, among more) were added?

**Comment by noahbass** [comment]
Bumped version to 1.0.0. Good to merge?

**Comment by domfarolino** [comment]
Go4it

**Comment by kurtlewis** [comment]
hold up! big errors on my page

**Comment by kurtlewis** [comment]
So the rendering on bosley.club looks **ABSOLUTELY AMAZING** but this is what it looks like when I run dev on my machine:

image

**Comment by kurtlewis** [comment]
Aaaannnddd I was missing dependencies. Looks amazing fantastic work all of you.

**Pull request merged**
