### PR TITLE
Feature/Add subtitle [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by isiah-lloyd**
I'm making this for discussion on the subtitle added onto the masthead.
image

@domfarolino What's a solution so that `Router.js` removes the secondary subtitle if it is not defined? Right now the secondary subtitle sticks if it's not defined. A solution is to define secondary_subtitle as an empty string but that would leave a large empty space between the bottom of the masthead and the text. 

@noahbass Font suggestions?

### CODE REVIEW

**Comment by domfarolino** [comment]
Idk if its just when I pull it down or what, but route navigation does not work and the masthead text being more centered than all the way to the left (a recent change I made this week) was not kept. Do you see this too @noahbass @isiah-lloyd ?

**Comment by domfarolino** [comment]
I removed my directory and re-pulled. I ran `npm install` on master and everything looked good when `dev` was running. I checked out this branch, ran `npm install` again just in case, then ran `dev` and the masthead did not seem to be rebased with master(?) and consequently route navigation failed. I can try and merge master into this branch and fix the issues if you want.

**Comment by domfarolino** [comment]
@isiah-lloyd I fixed the routing issue. We just need to re-style the masthead so the `h3` titles are smaller (presumably), and `h1` and `h3` have media queries on them. I'll let you take care of this and we can merge this. /cc @noahbass

**Comment by isiah-lloyd** [comment]
@domfarolino Why did you change the styles? Was it required for the router changes? Because it messed up the styles but I can make a workaround if it was needed.

**Comment by domfarolino** [comment]
In master, inside the `div.masthead` (the entire masthead) we have have a `div.masthead-title` which is a div wrapping the title `h1`. In your branch, you added an `h1`, and 2x`h3` which was good, but the internal div no longer had the class `masthead-title`. This meant the style was not affecting (or pushing the title(s) to the left anymore, and the font-size was a little off) so I made sure that the styles were more representative of how they are in master, while keeping the new masthead subtitle and location information that you added. Does that kinda make sense?

**Comment by isiah-lloyd** [comment]
What media queries are needed? This is how it looks on mobile right now: 
localhost-8080- iphone 6.

**Comment by domfarolino** [comment]
Yeah that looks fine. @noahbass how do you feel about serif. I'm starting to wonder if we should just go back to regular `Jockey One`. I feel like it might not look that bad.

@isiah-lloyd I think we should put some bottom-padding on the last element inside the masthead title.

screenshot from 2017-01-13 17-49-44

**Pull request merged**
